name: CI

on: [push]

jobs:
  repo-test:
    runs-on: ubuntu-latest
    name: Run tests on python repo

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r pipRequirements.txt
        
      - name: Python Tests (3.8)
        run: python -m unittest discover src/python_sim
